services:
  postgres:
    image: postgres:15-alpine
    container_name: rails_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2019.plA
      POSTGRES_DB: farmacia_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rails_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: rails_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    expose:
      - "3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:2019.plA@postgres:5432/farmacia_production
      REDIS_URL: redis://redis:6379/0
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  evolution_api:
    image: atendai/evolution-api:1.7.4
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Configurações básicas
      SERVER_URL: http://159.65.190.78:8080
      #CORS_ORIGIN: "*"
      #CORS_CREDENTIALS: "true"
      AUTHENTICATION_TYPE: "apikey"

      AUTHENTICATION_API_KEY: "teste1234"
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"

      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://postgres:2019.plA@postgres:5432/evolution_db
      DATABASE_CONNECTION_CLIENT_NAME: "evolution"
      DATABASE_SAVE_DATA_INSTANCE: "true"
      DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
      DATABASE_SAVE_MESSAGE_UPDATE: "true"
      DATABASE_SAVE_DATA_CONTACTS: "true"
      DATABASE_SAVE_DATA_CHATS: "true"
      REDIS_ENABLED: "true"
      REDIS_URI: redis://redis:6379
      # Adicione suas outras variáveis de ambiente aqui
      
      # Webhook
      WEBHOOK_GLOBAL_URL: ""
      WEBHOOK_GLOBAL_ENABLED: "false"
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: "false"
      
      # Logs
      LOG_LEVEL: "ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS"
      LOG_COLOR: "true"
      LOG_BAILEYS: "error"
      
      # Instance
      DEL_INSTANCE: "false"
    volumes:
      - evolution_data:/evolution/instances
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    depends_on:
      - redis
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - evolution_api
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  evolution_data:
  evolution_instances:  # ← Adicionar


networks:
  app_network:
    driver: bridge
