services:
  - type: web
    name: farmacia
    env: ruby
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: farmacia-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: farmacia-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: farmacia-db
    databaseName: farmacia_production
    user: farmacia

  - name: farmacia-redis
    plan: free